/**
 * Exports the last 30 days of per-model token usage from Zcode's local SQLite database into
 * `src/data/token-usage.json`, which the site prices with `src/data/model-prices.json`.
 *
 *   npm run usage:export            # dry run: prints the summary, writes nothing
 *   npm run usage:export -- --write # writes the JSON
 *   ZCODE_DB=/path/db.sqlite npm run usage:export -- --days 60 --write
 *
 * The database is opened read-only. Rows are grouped by model id only (the same model reached
 * through two provider accounts is one model), and only completed requests are counted. Call counts,
 * session, provider and message ids are never exported.
 *
 * Token semantics, as Zcode records them: `input` already includes cache reads and cache
 * writes, and `output` already includes reasoning.
 */
import { writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';

const OUT_PATH = fileURLToPath(new URL('../src/data/token-usage.json', import.meta.url));
const DB_PATH = process.env.ZCODE_DB ?? join(homedir(), '.zcode', 'cli', 'db', 'db.sqlite');

const write = process.argv.includes('--write');
const daysFlag = process.argv.indexOf('--days');
const days = daysFlag > -1 ? Number(process.argv[daysFlag + 1]) : 30;
if (!Number.isInteger(days) || days < 1) {
  console.error('--days must be a positive integer');
  process.exit(1);
}

const now = Date.now();
const since = now - days * 24 * 60 * 60 * 1000;
const db = new DatabaseSync(DB_PATH, { readOnly: true });
const rows = db
  .prepare(
    `select model_id as id,
            sum(input_tokens) as input,
            sum(output_tokens) as output,
            sum(reasoning_tokens) as reasoning,
            sum(cache_read_input_tokens) as cacheRead,
            sum(cache_creation_input_tokens) as cacheWrite
       from model_usage
      where status = 'completed' and started_at >= ?
      group by lower(model_id)
     having sum(input_tokens) + sum(output_tokens) > 0
      order by sum(input_tokens) + sum(output_tokens) desc`,
  )
  .all(since);
db.close();

const isoDay = (ms) => new Date(ms).toISOString().slice(0, 10);
const usage = {
  $comment:
    "Generated by `npm run usage:export -- --write` from Zcode's model_usage table. Do not edit by hand.",
  source: 'zcode',
  days,
  from: isoDay(since),
  to: isoDay(now),
  models: Object.fromEntries(
    rows.map(({ id, ...counts }) => [
      id,
      Object.fromEntries(Object.entries(counts).map(([k, v]) => [k, Number(v)])),
    ]),
  ),
};

for (const [id, m] of Object.entries(usage.models)) {
  console.log(
    `${id.padEnd(36)} ${(m.input / 1e6).toFixed(1).padStart(7)}M in  ${(m.output / 1e6).toFixed(2).padStart(6)}M out`,
  );
}
console.log(`${rows.length} models, ${usage.from} to ${usage.to}`);

if (write) {
  writeFileSync(OUT_PATH, `${JSON.stringify(usage, null, 2)}\n`);
  console.log(`Wrote ${OUT_PATH}`);
} else {
  console.log('Dry run — re-run with --write to save.');
}
